#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

menu_prompt = <<EOS
Hey, Movie Lover! What would you like to do?
1. Watch a movie
2. Add to your list
3. View your list
4. Edit your list
5. Review a movie
6. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
  say("Hey, Movie Lover! What would you like to do?\n")

  loop do
    choose do |menu|
      menu.prompt = ""

      movies_controller = MoviesController.new
      menu.choice('Watch a movie') do
        movies_controller.watch_prompt
      end
      menu.choice('Add to your list') do
        movies_controller.prompt
      end
      menu.choice('View your list') do
        say(movies_controller.index)
      end
      menu.choice('Edit your list') do
        movies_controller.edit_menu
      end
      menu.choice('Review a movie') do
        say("Feature coming soon!\n")
      end
      menu.choice('Exit') do
        say("'I'll be back!'\n")
        exit
      end
    end
  end
elsif menu.choice.empty?
  puts "You must choose one of [1, 2, 3, 4, 5, 6, Watch a movie, Add to your list, View your list, Edit your list, Review a movie, Exit].
+? "
else
  puts "Ambiguous choice.  Please choose one of [1, 2, 3, 4, 5, 6, Watch a movie, Add to your list, View your list, Edit your list, Review a movie, Exit].
+?  "
end
